# image: node:latest

# stages:
#   - build

# publish-package:
#   stage: build
#   before_script:
#     - npm install -g pnpm
#     - pnpm install
#   script:
#     - npm config set //gitlab.com/api/v4/projects/74368170/packages/npm/:_authToken ${api_types_npm}
#     - echo "@kayou:registry=https://gitlab.com/api/v4/projects/74368170/packages/npm/" > .npmrc
#     - pnpm build
#     - npm publish
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
